[package]
name = "astreuos-node"
version = "0.1.0"
edition = "2018"

[dependencies]
# stellar-notation = "0.9.6"
# neutrondb = "0.9.8"
neutrondb = { path = "../neutrondb-rs" }
stellar-notation = { path = "../stellar-notation-rs" }
rand = "0.8.4"
sha3 = "0.9.1"
ring = "0.16.20"
secp256k1 = "0.20.3"